# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Light Spacetime
email: qq0457@github.com
description: > # this means to ignore newlines until "baseurl:"
  Hero is an awesome description for my standalone blog here. 
  Even though I have no any idea about writing anyhing here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://light0457.github.io/" # the base hostname & protocol for your site
github_username:  light0457

# Build settings
markdown: kramdown
